// "Most At-Risk Roles 2026" report page (L4.2). Renders the ranking that
// `scripts/rank-at-risk.mjs` (L4.1a) writes to
// `data/report/most-at-risk-2026.json`, most at-risk first, with a per-role
// survival-score bar chart, a methodology pointer, and a deep link to each
// role's `/role/<slug>` forecast.
//
// Self-maintaining, same philosophy as `app/sitemap.ts` (D-027) and
// `scripts/rank-at-risk.mjs` (D-029): the ranking artifact does not exist
// today (it is generated by the human-gated post-seed L4.1b), so this page
// renders a stable, indexable "report is generating" state now and fills in
// with the real ranking the instant L4.1b commits the JSON — no code change.
// It deliberately does NOT `notFound()` on the missing file: unlike a bogus
// `/role/<slug>`, `/report/2026` is a real landing page that should always
// resolve 200 so its URL can be linked, shared, and indexed before the data
// lands.

import { promises as fs } from "node:fs";
import path from "node:path";

import type { Metadata } from "next";

import { EmailCapture } from "@/components/email-capture";
import type { ConfidenceLevel } from "@/lib/scoring/types";

const REPORT_YEAR = 2026;
const REPORT_TITLE = `Most At-Risk Roles ${REPORT_YEAR}`;
const REPORT_BLURB =
  "The roles current-gen AI is compressing fastest — ranked by survival score, soonest tipping point first.";

// Shape of `data/report/most-at-risk-2026.json` as emitted by
// `scripts/rank-at-risk.mjs`. Typed here (not imported) because the producer
// is a standalone Node stdlib script with no shared module — same
// scope-control call as the duplicated band thresholds below (D-029).
interface RankedRole {
  rank: number;
  slug: string;
  title: string;
  score: number;
  band: string;
  countdown_years: number;
  confidence: ConfidenceLevel | "unknown";
}

interface ReportPayload {
  meta: {
    report_year: number;
    title: string;
    generated_at: string;
    total_seeded: number;
    ranked: number;
    ranking_key: string[];
    source: string;
    note?: string;
  };
  roles: RankedRole[];
}

// Band → Tailwind classes, keyed by the exact label strings
// `rank-at-risk.mjs` writes ("Urgent" <20, "At-risk" <40, "Contested" <60,
// "Durable" <80, "Stable" >=80). Colours mirror `components/result-card.tsx`
// `bandFor()` so the report and the role page agree visually. Duplicated, not
// imported: `result-card.tsx` is a `"use client"` component and the producer
// is a stdlib script — same deliberate scope control as D-027/D-028/D-029.
const BAND_STYLE: Record<string, { bar: string; pill: string }> = {
  Urgent: {
    bar: "bg-red-500",
    pill: "bg-red-500/10 text-red-600 dark:text-red-400 border-red-500/30",
  },
  "At-risk": {
    bar: "bg-orange-500",
    pill: "bg-orange-500/10 text-orange-600 dark:text-orange-400 border-orange-500/30",
  },
  Contested: {
    bar: "bg-amber-500",
    pill: "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/30",
  },
  Durable: {
    bar: "bg-emerald-500",
    pill: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/30",
  },
  Stable: {
    bar: "bg-sky-500",
    pill: "bg-sky-500/10 text-sky-600 dark:text-sky-400 border-sky-500/30",
  },
};

const FALLBACK_STYLE = {
  bar: "bg-[var(--color-muted-foreground)]",
  pill: "bg-[var(--color-muted)] text-[var(--color-muted-foreground)] border-[var(--color-border)]",
};

export const metadata: Metadata = {
  title: `${REPORT_TITLE} — AI obsolescence ranking`,
  description: REPORT_BLURB,
  openGraph: {
    title: `${REPORT_TITLE} · halflife`,
    description: REPORT_BLURB,
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: `${REPORT_TITLE} · halflife`,
    description: REPORT_BLURB,
  },
};

async function loadReport(): Promise<ReportPayload | null> {
  try {
    const filePath = path.join(
      process.cwd(),
      "data",
      "report",
      `most-at-risk-${REPORT_YEAR}.json`,
    );
    const raw = await fs.readFile(filePath, "utf8");
    const parsed = JSON.parse(raw) as ReportPayload;
    if (!Array.isArray(parsed.roles)) return null;
    return parsed;
  } catch {
    // No artifact yet — L4.1b (post-seed) has not run. Self-maintaining
    // empty state below; not a 404.
    return null;
  }
}

function formatGeneratedAt(iso: string): string {
  const d = new Date(iso);
  return Number.isNaN(d.getTime())
    ? iso
    : d.toISOString().slice(0, 10); // YYYY-MM-DD, locale-stable for SSG
}

export default async function ReportPage() {
  const report = await loadReport();
  const roles = report?.roles ?? [];

  return (
    <main className="mx-auto flex min-h-screen max-w-3xl flex-col px-6 py-16">
      <header>
        <p className="text-xs uppercase tracking-wider text-[var(--color-muted-foreground)]">
          halflife · annual report
        </p>
        <h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">
          {REPORT_TITLE}
        </h1>
        <p className="mt-3 text-base text-[var(--color-muted-foreground)] sm:text-lg">
          {REPORT_BLURB}
        </p>
        {report && roles.length > 0 && (
          <p className="mt-4 text-xs text-[var(--color-muted-foreground)]">
            {report.meta.ranked} of {report.meta.total_seeded} seeded roles
            ranked · generated {formatGeneratedAt(report.meta.generated_at)}
          </p>
        )}
      </header>

      {roles.length === 0 ? (
        <section className="mt-12 rounded-xl border border-dashed border-[var(--color-border)] bg-[var(--color-muted)]/20 p-6">
          <h2 className="text-sm font-semibold">Report is still generating</h2>
          <p className="mt-2 text-sm text-[var(--color-muted-foreground)]">
            The {REPORT_YEAR} ranking is computed from the precomputed role
            forecasts. The seed pass that produces them has not run yet, so
            there is nothing to rank. This page auto-populates the moment the
            ranking lands — no need to revisit a different URL.
          </p>
          <p className="mt-4 text-sm">
            In the meantime,{" "}
            <a
              href="/"
              className="underline decoration-dotted underline-offset-4 hover:text-[var(--color-foreground)]"
            >
              score any role yourself →
            </a>
          </p>
        </section>
      ) : (
        <section
          aria-labelledby="ranking-heading"
          className="mt-12 flex flex-col gap-3"
        >
          <h2 id="ranking-heading" className="sr-only">
            Ranking, most at-risk first
          </h2>
          <ol className="flex flex-col gap-2">
            {roles.map((r) => {
              const style = BAND_STYLE[r.band] ?? FALLBACK_STYLE;
              const width = Math.max(0, Math.min(100, r.score));
              return (
                <li
                  key={r.slug}
                  className="rounded-lg border border-[var(--color-border)] bg-[var(--color-muted)]/30 px-4 py-3"
                >
                  <div className="flex items-baseline justify-between gap-3">
                    <p className="min-w-0 flex items-baseline gap-2">
                      <span className="text-xs tabular-nums text-[var(--color-muted-foreground)]">
                        #{r.rank}
                      </span>
                      <a
                        href={`/role/${r.slug}`}
                        className="truncate font-medium capitalize underline decoration-dotted underline-offset-4 hover:text-[var(--color-foreground)]"
                      >
                        {r.title}
                      </a>
                    </p>
                    <span
                      className={`inline-flex shrink-0 items-center rounded-full border px-2 py-0.5 text-[10px] font-medium ${style.pill}`}
                    >
                      {r.band}
                    </span>
                  </div>
                  <div
                    className="mt-2 h-1.5 w-full overflow-hidden rounded-full bg-[var(--color-border)]"
                    role="meter"
                    aria-valuemin={0}
                    aria-valuemax={100}
                    aria-valuenow={r.score}
                    aria-label={`${r.title}: survival score ${r.score} of 100 (${r.band})`}
                  >
                    <div
                      className={`h-full rounded-full ${style.bar}`}
                      style={{ width: `${width}%` }}
                    />
                  </div>
                  <p className="mt-1.5 flex flex-wrap gap-x-3 text-[11px] text-[var(--color-muted-foreground)]">
                    <span className="tabular-nums">
                      score {r.score}/100
                    </span>
                    <span aria-hidden="true">·</span>
                    <span className="tabular-nums">
                      {r.countdown_years.toFixed(1)} yrs to tipping point
                    </span>
                    <span aria-hidden="true">·</span>
                    <span>{r.confidence} confidence</span>
                  </p>
                </li>
              );
            })}
          </ol>
        </section>
      )}

      <section
        aria-labelledby="capture-heading"
        className="mt-12 rounded-xl border border-[var(--color-border)] bg-[var(--color-muted)]/20 p-6"
      >
        <h2 id="capture-heading" className="text-sm font-semibold">
          Get the {REPORT_YEAR} ranking when it lands
        </h2>
        <p className="mt-2 mb-4 text-sm text-[var(--color-muted-foreground)]">
          One email when the ranking is published or materially shifts. No
          newsletter, no drip — the share card is the product, not an audience
          funnel.
        </p>
        <EmailCapture source={`report-${REPORT_YEAR}`} />
      </section>

      <section
        aria-labelledby="methodology-heading"
        className="mt-12 border-t border-[var(--color-border)] pt-6"
      >
        <h2
          id="methodology-heading"
          className="text-xs font-semibold uppercase tracking-wider text-[var(--color-muted-foreground)]"
        >
          How this ranking is built
        </h2>
        <p className="mt-2 text-sm text-[var(--color-muted-foreground)]">
          Each role is scored 0–100 for survivability (higher = more durable),
          then ranked ascending by{" "}
          <span className="text-[var(--color-foreground)]">survival score</span>
          , breaking ties on the{" "}
          <span className="text-[var(--color-foreground)]">
            soonest AI tipping point
          </span>{" "}
          then title. The band is the same five-step taxonomy the role pages
          use: Urgent (&lt;20), At-risk (&lt;40), Contested (&lt;60), Durable
          (&lt;80), Stable (≥80). Full scoring dimensions and disclaimers are
          in <code>docs/methodology.md</code>.
        </p>
      </section>

      <footer className="mt-auto pt-12 text-xs text-[var(--color-muted-foreground)]">
        <a
          href="/"
          className="underline decoration-dotted underline-offset-4 hover:text-[var(--color-foreground)]"
        >
          Score another role →
        </a>
      </footer>
    </main>
  );
}
